data_pipeline:
  target: dev
  outputs:
    dev:
      type: snowflake
      role: 'DBT_ROLE'
      warehouse: 'DBT_WH'
      database: 'TEST_WAREHOUSE'
      schema: 'DBT_SCHEMA'
      account: ' '
      user: ' '
