select 
O_ORDERKEY AS ORDER_KEY
,O_CUSTKEY AS CUSTOMER_KEY
,O_ORDERSTATUS AS STATUS
,O_TOTALPRICE AS TOTAL_PRICE
,O_ORDERDATE AS ORDER_DATE
,'TPCH_SF1' AS DATA_SOURCE
from 
    {{ source('tpch_sf1','orders')}}