select 
L_ORDERKEY AS ORDER_KEY
,L_PARTKEY AS PART_KEY
,L_LINENUMBER AS LINE_NUMBER
,L_QUANTITY AS QUANTITY
,L_EXTENDEDPRICE AS EXTENDED_PRICE
,L_DISCOUNT AS DISCOUNT
,L_TAX AS TAX
,L_RETURNFLAG AS RETURN_FLAG
,L_LINESTATUS AS LINE_STATUS
,L_SHIPDATE AS SHIP_DATE
,'TPCH_SF1' AS DATA_SOURCE
from
    {{ source('tpch_sf1','lineitem')}}